#!/usr/bin/python
import json

# Load json containing info about the website
f = open('data.json', 'r')
s = f.read()
f.close()

data = json.loads(s)

data['visits'] = 0
for os in data['OS']:
    data['OS'][os] = 0
for br in data['Browser']:
    data['Browser'][br] = 0
for la in data['Language']:
    data['Language'][la] = 0
data['IPs'] = []
data['unique_visits'] = 0

f = open('data.json', 'w')
f.write(json.dumps(data))
f.close()
