#!/usr/bin/python
import json

# Load json containing info about the website
f = open('data.json', 'r')
s = f.read()
f.close()

data = json.loads(s)

data['visits'] = 0
data['OS']['MAC'] = 0
data['OS']['WINDOWS'] = 0
data['OS']['iOS'] = 0
data['OS']['OTHER'] = 0
data['IPs'] = []
data['unique_visits'] = 0

f = open('data.json', 'w')
f.write(json.dumps(data))
f.close()
